add optional initialSlide (index) property
kidwm/react-flex-carousel pull request #13
Opened 2017-11-14 17:54 UTC by mikejw

2017-11-15 02:17 UTC, kidwm requested changes

2017-11-15 02:17 UTC, kidwm commented on carousel.js
> +		this.state = {slide: props.initialSlide || 1, dragging: null, sliding: false, offset: 0}; // slide index start from 1
I think it is better to declare default value in `defaultProps`

2017-11-15 13:30 UTC, mikejw commented
Hi, this is committed (and squashed) now.

2017-11-16 01:44 UTC, kidwm approved these changes

2017-11-16 01:45 UTC, merged